### ISSUE TITLE
Visualization of Topic/Word Modeling

### ISSUE THREAD

**Issue by credgeco** [UNCG-CSE/Podknow#33]
Create graphs that can be used to show changes in our topic data.

**Comment by credgeco** [comment]
Create LSA models for each individual podcast. (Harini)

LDA models will be created for each individual podcast. (Chris, Jeremy)

Graphs for topic of all 200 podcasts LDA/LSA.

Coherence score graph for each podcast LDA/LSA. (Harini, Chris, Jeremy)

**Comment by JeremyHudson43** [comment]
Fixed with commit 3db596a5d0d7e2e2ec317711abba86577d69e522
